# Generated by Django 4.2.20 on 2026-02-09 09:26

from django.db import migrations, models
import django.db.models.deletion
import drawings.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon_shape', models.CharField(choices=[('circle', 'Circle'), ('square', 'Square'), ('triangle', 'Triangle'), ('star', 'Star'), ('diamond', 'Diamond'), ('custom', 'Custom Image')], default='circle', max_length=20)),
                ('custom_icon', models.ImageField(blank=True, help_text='Custom icon image (PNG/JPG)', null=True, upload_to='icons/', validators=[drawings.validators.ImageFileValidator(max_size=5242880)])),
                ('color', models.CharField(default='#FF0000', help_text='Hex color code', max_length=7)),
                ('size', models.PositiveIntegerField(default=20, help_text='Icon size in pixels')),
            ],
            options={
                'verbose_name': 'Asset Type',
                'verbose_name_plural': 'Asset Types',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pixels_per_meter', models.FloatField(default=100.0, help_text='Scale factor from pixels to meters')),
                ('scale_calibrated', models.BooleanField(default=False, help_text='Whether scale has been explicitly calibrated')),
                ('coord_unit', models.CharField(choices=[('meters', 'Meters'), ('degrees', 'Lat/Lon Degrees (WGS84)'), ('gda94_geo', 'GDA94 Geographic (Lat/Lon)'), ('gda94_mga', 'GDA94 MGA (Easting/Northing)')], default='meters', help_text='Unit of asset coordinates: meters or lat/lon degrees', max_length=10)),
                ('origin_x', models.FloatField(default=0.0, help_text='X coordinate of origin in pixels')),
                ('origin_y', models.FloatField(default=0.0, help_text='Y coordinate of origin in pixels')),
                ('canvas_rotation', models.FloatField(default=0.0, help_text='Viewport rotation in degrees')),
                ('asset_rotation', models.FloatField(default=0.0, help_text='Asset layer rotation in degrees')),
                ('ref_asset_id', models.CharField(blank=True, default='', help_text='Asset ID of the reference point asset', max_length=100)),
                ('ref_pixel_x', models.FloatField(default=0.0, help_text='Pixel X where reference asset was placed on canvas')),
                ('ref_pixel_y', models.FloatField(default=0.0, help_text='Pixel Y where reference asset was placed on canvas')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('pdf_file', models.FileField(upload_to='pdfs/', validators=[drawings.validators.PDFFileValidator(max_size=52428800)])),
                ('page_number', models.PositiveIntegerField(default=1, help_text='Page number within the PDF')),
                ('rendered_image', models.ImageField(blank=True, null=True, upload_to='rendered/')),
                ('image_width', models.PositiveIntegerField(default=0)),
                ('image_height', models.PositiveIntegerField(default=0)),
                ('cuts_json', models.JSONField(blank=True, default=list, help_text='Array of cut definitions: [{p1: {x, y}, p2: {x, y}, flipped: bool}, ...]')),
                ('offset_x', models.FloatField(default=0.0, help_text='X offset in pixels')),
                ('offset_y', models.FloatField(default=0.0, help_text='Y offset in pixels')),
                ('rotation', models.FloatField(default=0.0, help_text='Rotation in degrees')),
                ('z_index', models.IntegerField(default=0, help_text='Layer order (higher = on top)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheets', to='drawings.project')),
            ],
            options={
                'ordering': ['z_index', 'name'],
            },
        ),
        migrations.CreateModel(
            name='JoinMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('reference_label', models.CharField(max_length=255)),
                ('linked_mark', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_from', to='drawings.joinmark')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_marks', to='drawings.sheet')),
            ],
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset_count', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_batches', to='drawings.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ColumnPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('asset_id', 'Asset ID'), ('asset_type', 'Asset Type'), ('x', 'X Coordinate'), ('y', 'Y Coordinate'), ('name', 'Name (optional)')], max_length=20)),
                ('column_name', models.CharField(help_text='CSV column header that maps to this role', max_length=100)),
                ('priority', models.IntegerField(default=0, help_text='Higher = preferred when multiple matches')),
            ],
            options={
                'verbose_name': 'Column Preset',
                'verbose_name_plural': 'Column Presets',
                'ordering': ['role', '-priority'],
                'unique_together': {('role', 'column_name')},
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(max_length=100)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('original_x', models.FloatField()),
                ('original_y', models.FloatField()),
                ('adjusted_x', models.FloatField(blank=True, null=True)),
                ('adjusted_y', models.FloatField(blank=True, null=True)),
                ('is_adjusted', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='drawings.assettype')),
                ('import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='drawings.importbatch')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='drawings.project')),
            ],
            options={
                'ordering': ['asset_id'],
                'unique_together': {('project', 'asset_id')},
            },
        ),
        migrations.CreateModel(
            name='AdjustmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_x', models.FloatField()),
                ('from_y', models.FloatField()),
                ('to_x', models.FloatField()),
                ('to_y', models.FloatField()),
                ('delta_x', models.FloatField()),
                ('delta_y', models.FloatField()),
                ('delta_distance', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustment_logs', to='drawings.asset')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
