# Generated by Django 4.2.28 on 2026-02-05 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon_shape', models.CharField(choices=[('circle', 'Circle'), ('square', 'Square'), ('triangle', 'Triangle'), ('star', 'Star'), ('diamond', 'Diamond'), ('custom', 'Custom Image')], default='circle', max_length=20)),
                ('custom_icon', models.ImageField(blank=True, help_text='Custom icon image (PNG/JPG)', null=True, upload_to='icons/')),
                ('color', models.CharField(default='#FF0000', help_text='Hex color code', max_length=7)),
                ('size', models.PositiveIntegerField(default=20, help_text='Icon size in pixels')),
            ],
            options={
                'verbose_name': 'Asset Type',
                'verbose_name_plural': 'Asset Types',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pixels_per_meter', models.FloatField(default=100.0, help_text='Scale factor from pixels to meters')),
                ('origin_x', models.FloatField(default=0.0, help_text='X coordinate of origin in pixels')),
                ('origin_y', models.FloatField(default=0.0, help_text='Y coordinate of origin in pixels')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('pdf_file', models.FileField(upload_to='pdfs/')),
                ('page_number', models.PositiveIntegerField(default=1, help_text='Page number within the PDF')),
                ('rendered_image', models.ImageField(blank=True, null=True, upload_to='rendered/')),
                ('image_width', models.PositiveIntegerField(default=0)),
                ('image_height', models.PositiveIntegerField(default=0)),
                ('crop_x', models.FloatField(default=0.0)),
                ('crop_y', models.FloatField(default=0.0)),
                ('crop_width', models.FloatField(default=0.0, help_text='0 means full width')),
                ('crop_height', models.FloatField(default=0.0, help_text='0 means full height')),
                ('offset_x', models.FloatField(default=0.0, help_text='X offset in pixels')),
                ('offset_y', models.FloatField(default=0.0, help_text='Y offset in pixels')),
                ('rotation', models.FloatField(default=0.0, help_text='Rotation in degrees')),
                ('z_index', models.IntegerField(default=0, help_text='Layer order (higher = on top)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheets', to='drawings.project')),
            ],
            options={
                'ordering': ['z_index', 'name'],
            },
        ),
        migrations.CreateModel(
            name='JoinMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('reference_label', models.CharField(max_length=255)),
                ('linked_mark', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_from', to='drawings.joinmark')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_marks', to='drawings.sheet')),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(max_length=100)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('original_x', models.FloatField()),
                ('original_y', models.FloatField()),
                ('adjusted_x', models.FloatField(blank=True, null=True)),
                ('adjusted_y', models.FloatField(blank=True, null=True)),
                ('is_adjusted', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='drawings.assettype')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='drawings.project')),
            ],
            options={
                'ordering': ['asset_id'],
                'unique_together': {('project', 'asset_id')},
            },
        ),
        migrations.CreateModel(
            name='AdjustmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_x', models.FloatField()),
                ('from_y', models.FloatField()),
                ('to_x', models.FloatField()),
                ('to_y', models.FloatField()),
                ('delta_x', models.FloatField()),
                ('delta_y', models.FloatField()),
                ('delta_distance', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustment_logs', to='drawings.asset')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
