# Generated by Django 4.2.20 on 2026-02-17 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drawings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_id', models.CharField(max_length=100)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('coordinates', models.JSONField(help_text='Array of [longitude, latitude] coordinate pairs, e.g. [[145.74, -16.96], [145.75, -16.95]]')),
                ('color', models.CharField(default='#0066FF', help_text='Hex color code', max_length=7)),
                ('width', models.PositiveIntegerField(default=2, help_text='Line width in pixels')),
                ('opacity', models.FloatField(default=1.0, help_text='Opacity from 0.0 to 1.0')),
                ('link_type', models.CharField(choices=[('pipe', 'Pipe'), ('cable', 'Cable'), ('conduit', 'Conduit'), ('duct', 'Duct'), ('main', 'Main'), ('service', 'Service'), ('other', 'Other')], default='other', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='links', to='drawings.importbatch')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='drawings.project')),
            ],
            options={
                'ordering': ['link_id'],
                'unique_together': {('project', 'link_id')},
            },
        ),
    ]
