# Generated by Django 4.2.20 on 2026-02-17 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cadastre_cache_timestamp',
            field=models.DateTimeField(blank=True, help_text='Last time cadastre data was fetched', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='cadastre_color',
            field=models.CharField(default='#FF0000', help_text='Hex color for cadastre boundaries', max_length=7),
        ),
        migrations.AddField(
            model_name='project',
            name='cadastre_enabled',
            field=models.BooleanField(default=False, help_text='Enable Queensland cadastre boundary overlay'),
        ),
        migrations.AddField(
            model_name='project',
            name='cadastre_opacity',
            field=models.FloatField(default=0.5, help_text='Opacity of cadastre layer (0-1)'),
        ),
    ]
