# Generated by Django 4.2.28 on 2026-02-06 02:02

from django.db import migrations, models
import drawings.validators


class Migration(migrations.Migration):

    dependencies = [
        ('drawings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='canvas_rotation',
            field=models.FloatField(default=0.0, help_text='Viewport rotation in degrees'),
        ),
        migrations.AlterField(
            model_name='assettype',
            name='custom_icon',
            field=models.ImageField(blank=True, help_text='Custom icon image (PNG/JPG)', null=True, upload_to='icons/', validators=[drawings.validators.ImageFileValidator(max_size=5242880)]),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='pdf_file',
            field=models.FileField(upload_to='pdfs/', validators=[drawings.validators.PDFFileValidator(max_size=52428800)]),
        ),
    ]
