# Generated by Django 4.2.28 on 2026-02-06 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawings', '0002_add_canvas_rotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='crop_flipped',
            field=models.BooleanField(default=False, help_text='Which side of cut line to show'),
        ),
    ]
