# Generated by Django 4.2.20 on 2026-02-18 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drawings', '0002_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('measurement_type', models.CharField(choices=[('single', 'Single Measurement'), ('chain', 'Chain Measurement')], default='single', max_length=10)),
                ('points', models.JSONField(default=list, help_text='Array of {x, y} canvas coordinate points')),
                ('color', models.CharField(default='#00bcd4', help_text='Line/point color', max_length=7)),
                ('visible', models.BooleanField(default=True)),
                ('total_distance_pixels', models.FloatField(blank=True, null=True)),
                ('total_distance_meters', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurement_sets', to='drawings.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LayerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('group_type', models.CharField(choices=[('asset', 'Asset Group'), ('link', 'Link Group')], max_length=10)),
                ('color', models.CharField(default='#3498db', help_text='Color for UI display', max_length=7)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('import_batch', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='layer_group', to='drawings.importbatch')),
                ('parent_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_groups', to='drawings.layergroup')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layer_groups', to='drawings.project')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='layer_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='drawings.layergroup'),
        ),
        migrations.AddField(
            model_name='link',
            name='layer_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='links_in_group', to='drawings.layergroup'),
        ),
    ]
