# Generated by Django 4.2.20 on 2026-02-18 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drawings', '0003_layergroup_measurementset'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='layer_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sheets_in_group', to='drawings.layergroup'),
        ),
        migrations.AlterField(
            model_name='layergroup',
            name='group_type',
            field=models.CharField(choices=[('asset', 'Asset Group'), ('link', 'Link Group'), ('sheet', 'Sheet Group')], max_length=10),
        ),
    ]
