# Generated by Django 4.2.20 on 2026-02-18 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawings', '0004_sheet_layer_group_alter_layergroup_group_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cadastre_color',
            field=models.CharField(default='#FF6600', help_text='Color for cadastre boundaries', max_length=7),
        ),
        migrations.AddField(
            model_name='project',
            name='cadastre_enabled',
            field=models.BooleanField(default=False, help_text='Enable cadastre overlay layer'),
        ),
    ]
