# Generated by Django 4.2.20 on 2026-02-18 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawings', '0005_project_cadastre_color_project_cadastre_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='crop_flipped',
            field=models.BooleanField(default=False, help_text='Whether the crop is flipped'),
        ),
    ]
