# Generated by Django 4.2.28 on 2026-02-06 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawings', '0005_remove_old_crop_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='asset_rotation',
            field=models.FloatField(default=0.0, help_text='Asset layer rotation in degrees'),
        ),
        migrations.AddField(
            model_name='project',
            name='ref_asset_id',
            field=models.CharField(blank=True, default='', help_text='Asset ID of the reference point asset', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='ref_pixel_x',
            field=models.FloatField(default=0.0, help_text='Pixel X where reference asset was placed on canvas'),
        ),
        migrations.AddField(
            model_name='project',
            name='ref_pixel_y',
            field=models.FloatField(default=0.0, help_text='Pixel Y where reference asset was placed on canvas'),
        ),
    ]
