# Generated by Django 4.2.20 on 2026-02-18 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawings', '0006_sheet_crop_flipped'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='osm_enabled',
            field=models.BooleanField(default=False, help_text='Enable OpenStreetMap tile layer'),
        ),
        migrations.AddField(
            model_name='project',
            name='osm_opacity',
            field=models.FloatField(default=0.7, help_text='Opacity of OSM layer (0.0 to 1.0)'),
        ),
        migrations.AddField(
            model_name='project',
            name='osm_z_index',
            field=models.IntegerField(default=0, help_text='Z-index for OSM layer ordering (0=bottom, higher=top)'),
        ),
    ]
