# Generated by Django 4.2.28 on 2026-02-06 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawings', '0006_add_asset_calibration'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('asset_id', 'Asset ID'), ('asset_type', 'Asset Type'), ('x', 'X Coordinate'), ('y', 'Y Coordinate'), ('name', 'Name (optional)')], max_length=20)),
                ('column_name', models.CharField(help_text='CSV column header that maps to this role', max_length=100)),
                ('priority', models.IntegerField(default=0, help_text='Higher = preferred when multiple matches')),
            ],
            options={
                'verbose_name': 'Column Preset',
                'verbose_name_plural': 'Column Presets',
                'ordering': ['role', '-priority'],
                'unique_together': {('role', 'column_name')},
            },
        ),
    ]
