# Generated by Django 4.2.20 on 2026-02-19 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drawings', '0007_project_osm_enabled_project_osm_opacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementset',
            name='layer_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='measurements_in_group', to='drawings.layergroup'),
        ),
    ]
