# Generated by Django 4.2.20 on 2026-02-19 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawings', '0008_measurementset_layer_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='layergroup',
            name='scope',
            field=models.CharField(choices=[('local', 'Local - Only visible in its own section'), ('global', 'Global - Shared across all sections')], default='local', help_text='Whether this folder is local to one section or global', max_length=10),
        ),
    ]
