# Generated by Django 4.2.20 on 2026-02-19 01:28

from django.db import migrations


def set_existing_to_global(apps, schema_editor):
    """Set all existing layer groups to global scope."""
    LayerGroup = apps.get_model('drawings', 'LayerGroup')
    LayerGroup.objects.all().update(scope='global')


def reverse_to_local(apps, schema_editor):
    """Revert all groups back to local scope."""
    LayerGroup = apps.get_model('drawings', 'LayerGroup')
    LayerGroup.objects.all().update(scope='local')


class Migration(migrations.Migration):

    dependencies = [
        ('drawings', '0009_layergroup_scope'),
    ]

    operations = [
        migrations.RunPython(set_existing_to_global, reverse_to_local),
    ]
