# Generated by Django 4.2.28 on 2026-02-09 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawings', '0009_importbatch_asset_import_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='coord_unit',
            field=models.CharField(choices=[('meters', 'Meters'), ('degrees', 'Lat/Lon Degrees')], default='meters', help_text='Unit of asset coordinates: meters or lat/lon degrees', max_length=10),
        ),
        migrations.AddField(
            model_name='project',
            name='scale_calibrated',
            field=models.BooleanField(default=False, help_text='Whether scale has been explicitly calibrated'),
        ),
    ]
