# Generated by Django 4.2.20 on 2026-02-19 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawings', '0010_set_existing_groups_to_global'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layergroup',
            name='group_type',
            field=models.CharField(choices=[('asset', 'Asset Group'), ('link', 'Link Group'), ('sheet', 'Sheet Group'), ('measurement', 'Measurement Group')], max_length=15),
        ),
    ]
