# Generated by Django 4.2.28 on 2026-02-09 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawings', '0011_seed_default_asset_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='coord_unit',
            field=models.CharField(choices=[('meters', 'Meters'), ('degrees', 'Lat/Lon Degrees (WGS84)'), ('gda94_geo', 'GDA94 Geographic (Lat/Lon)'), ('gda94_mga', 'GDA94 MGA (Easting/Northing)')], default='meters', help_text='Unit of asset coordinates: meters or lat/lon degrees', max_length=10),
        ),
    ]
