# Generated by Django 4.2.29 on 2026-04-02 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawings', '0011_alter_layergroup_group_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='pdf_layers',
            field=models.JSONField(blank=True, default=list, help_text='Available OCG layers: [{xref: int, name: str}, ...]'),
        ),
        migrations.AddField(
            model_name='sheet',
            name='visible_layers',
            field=models.JSONField(blank=True, default=list, help_text='List of visible layer xrefs (empty = all visible)'),
        ),
    ]
