# Generated by Django 4.2.29 on 2026-04-02 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawings', '0013_add_pdf_layers_to_sheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinmark',
            name='auto_detected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='joinmark',
            name='confidence',
            field=models.FloatField(default=1.0, help_text='Detection confidence 0-1'),
        ),
        migrations.AddField(
            model_name='joinmark',
            name='edge',
            field=models.CharField(blank=True, choices=[('top', 'Top'), ('bottom', 'Bottom'), ('left', 'Left'), ('right', 'Right')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='joinmark',
            name='shape',
            field=models.CharField(blank=True, choices=[('triangle', 'Triangle'), ('diamond', 'Diamond'), ('circle', 'Circle'), ('arrow', 'Arrow'), ('manual', 'Manual')], default='manual', max_length=10),
        ),
        migrations.AlterField(
            model_name='joinmark',
            name='reference_label',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
